# Generated by Django 4.1.7 on 2023-04-25 02:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0002_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="telephone",
            field=models.CharField(
                default="0000000000",
                max_length=10,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_telephone",
                        message="Telephone number must start with 0 and have 10 digits",
                        regex="^0\\d{9}$",
                    )
                ],
            ),
        ),
    ]
