# Generated by Django 4.1.7 on 2023-05-04 12:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Core", "0003_user_address_user_telephone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="telephone",
            field=models.CharField(
                max_length=10,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_telephone",
                        message="Telephone number must start with 0 and have 10 digits",
                        regex="^0\\d{9}$",
                    )
                ],
            ),
        ),
    ]
