# Generated by Django 4.1.7 on 2023-04-18 03:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=200)),
                ("first_name", models.CharField(default="fname", max_length=200)),
                ("last_name", models.CharField(default="lname", max_length=200)),
                ("password", models.CharField(max_length=100)),
                (
                    "telephone",
                    models.CharField(
                        default="0000000000",
                        max_length=10,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_telephone",
                                message="Telephone number must start with 0 and have 10 digits",
                                regex="^0\\d{9}$",
                            )
                        ],
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        default="mail",
                        max_length=200,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_email",
                                message='Email must end with "chula.ac.th"',
                                regex=".+@.+.chula.ac.th",
                            )
                        ],
                    ),
                ),
                ("address", models.CharField(max_length=200)),
            ],
        ),
    ]
