# Generated by Django 4.2 on 2023-04-18 13:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0003_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='telephone',
            field=models.CharField(default='0000000000', max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_telephone', message='Telephone number must start with 0 and have 10 digits', regex='^0\\d{9}$')]),
        ),
    ]
