# Generated by Django 4.1.7 on 2023-05-04 12:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Buyer", "0007_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="address",
        ),
        migrations.RemoveField(
            model_name="order",
            name="phone",
        ),
    ]
