# Generated by Django 4.1.7 on 2023-05-04 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Buyer", "0008_remove_order_address_remove_order_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="date",
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
